INSERT INTO public.t_province (province_code,province_name,province_name_en) VALUES
	 (11,'ACEH','ACEH'),
	 (12,'SUMATERA UTARA','NORTH SUMATERA'),
	 (13,'SUMATERA BARAT','WEST SUMATERA'),
	 (14,'RIAU','RIAU'),
	 (15,'JAMBI','JAMBI'),
	 (16,'SUMATERA SELATAN','SOUTH SUMATERA'),
	 (17,'BENGKULU','BENGKULU'),
	 (18,'LAMPUNG','LAMPUNG'),
	 (19,'KEPULAUAN BANGKA BELITUNG','BANGKA BELITUNG ISLANDS'),
	 (21,'KEPULAUAN RIAU','RIAU ISLANDS');
INSERT INTO public.t_province (province_code,province_name,province_name_en) VALUES
	 (31,'DAERAH KHUSUS IBUKOTA JAKARTA','SPECIAL CAPITAL REGION OF JAKARTA'),
	 (32,'JAWA BARAT','WEST JAVA'),
	 (33,'JAWA TENGAH','CENTRAL JAVA'),
	 (34,'DAERAH ISTIMEWA YOGYAKARTA','SEPCIAL REGION OF YOGYAKARTA'),
	 (35,'JAWA TIMUR','EAST JAVA'),
	 (36,'BANTEN','BANTEN'),
	 (51,'BALI','BALI'),
	 (52,'NUSA TENGGARA BARAT','WEST NUSA TENGGARA'),
	 (53,'NUSA TENGGARA TIMUR','EAST NUSA TENGGARA'),
	 (61,'KALIMANTAN BARAT','WEST KALIMANTAN');
INSERT INTO public.t_province (province_code,province_name,province_name_en) VALUES
	 (62,'KALIMANTAN TENGAH','CENTRAL KALIMANTAN'),
	 (63,'KALIMANTAN SELATAN','SOUTH KALIMANTAN'),
	 (64,'KALIMANTAN TIMUR','EAST KALIMANTAN'),
	 (65,'KALIMANTAN UTARA','NORTH KALIMANTAN'),
	 (71,'SULAWESI UTARA','NORTH SULAWESI'),
	 (72,'SULAWESI TENGAH','CENTRAL SULAWESI'),
	 (73,'SULAWESI SELATAN','SOUTH SULAWESI'),
	 (74,'SULAWESI TENGGARA','SOUTHEAST SULAWESI'),
	 (75,'GORONTALO','GORONTALO'),
	 (76,'SULAWESI BARAT','WEST SULAWESI');
INSERT INTO public.t_province (province_code,province_name,province_name_en) VALUES
	 (81,'MALUKU','MALUKU'),
	 (82,'MALUKU UTARA','NORTH MALUKU'),
	 (91,'PAPUA','PAPUA'),
	 (92,'PAPUA BARAT','WEST PAPUA');